version: '3'

services:
  mariadb:
    build: .
    image: custom/mariadb:10.6.8
    restart: always
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
      - sftp_data:/var/lib/mysql/upload
      - ./scripts/connect.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_MYSQL_LOCALHOST_USER=true
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -P 3306 -p${MARIADB_ROOT_PASSWORD} | grep 'mysqld is alive' || exit 1"]
      interval: 2s
      retries: 15
    ports:
      - "3306:3306"

  adminer:
    depends_on:
        mariadb:
          condition: service_healthy
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
    - sftp_data:/home/dw/upload
    ports:
      - "2222:22"
    command: dw:dw:1001

volumes:
  mariadb_data:
  sftp_data: